//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.Resources.Logic", typeof(Logic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactFormEmailSendFailed {
            get {
                return ResourceManager.GetString("ContactFormEmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContactFormEmailSendSuccess {
            get {
                return ResourceManager.GetString("ContactFormEmailSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External link.
        /// </summary>
        public static string ExternalLink {
            get {
                return ResourceManager.GetString("ExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileDeleteFailed {
            get {
                return ResourceManager.GetString("FileDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileDeleteSuccess {
            get {
                return ResourceManager.GetString("FileDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileInsertFailed {
            get {
                return ResourceManager.GetString("FileInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileInsertSuccess {
            get {
                return ResourceManager.GetString("FileInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileUpdateFailed {
            get {
                return ResourceManager.GetString("FileUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileUpdateSuccess {
            get {
                return ResourceManager.GetString("FileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local link.
        /// </summary>
        public static string LocalLink {
            get {
                return ResourceManager.GetString("LocalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuButtonDeleteFailed {
            get {
                return ResourceManager.GetString("MenuButtonDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuButtonDeleteSuccess {
            get {
                return ResourceManager.GetString("MenuButtonDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuButtonInsertFailed {
            get {
                return ResourceManager.GetString("MenuButtonInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuButtonInsertSuccess {
            get {
                return ResourceManager.GetString("MenuButtonInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuButtonUpdateFailed {
            get {
                return ResourceManager.GetString("MenuButtonUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuButtonUpdateSuccess {
            get {
                return ResourceManager.GetString("MenuButtonUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify news failed..
        /// </summary>
        public static string ModifyNewsFailed {
            get {
                return ResourceManager.GetString("ModifyNewsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify news succeed..
        /// </summary>
        public static string ModifyNewsSuccess {
            get {
                return ResourceManager.GetString("ModifyNewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModifyPageFailed {
            get {
                return ResourceManager.GetString("ModifyPageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModifyPageSuccess {
            get {
                return ResourceManager.GetString("ModifyPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user failed..
        /// </summary>
        public static string ModifyUserFailed {
            get {
                return ResourceManager.GetString("ModifyUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user succeed..
        /// </summary>
        public static string ModifyUserSuccess {
            get {
                return ResourceManager.GetString("ModifyUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsCategoryDeleteFailed {
            get {
                return ResourceManager.GetString("NewsCategoryDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsCategoryDeleteSuccess {
            get {
                return ResourceManager.GetString("NewsCategoryDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsCategoryInsertFailed {
            get {
                return ResourceManager.GetString("NewsCategoryInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsCategoryInsertSuccess {
            get {
                return ResourceManager.GetString("NewsCategoryInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsCategoryUpdateFailed {
            get {
                return ResourceManager.GetString("NewsCategoryUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsCategoryUpdateSuccess {
            get {
                return ResourceManager.GetString("NewsCategoryUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsletterReceiverDeleteFailed {
            get {
                return ResourceManager.GetString("NewsletterReceiverDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsletterReceiverDeleteSuccess {
            get {
                return ResourceManager.GetString("NewsletterReceiverDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsletterReceiverInsertFailed {
            get {
                return ResourceManager.GetString("NewsletterReceiverInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewsletterReceiverInsertSuccess {
            get {
                return ResourceManager.GetString("NewsletterReceiverInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PopUpInsertFailed {
            get {
                return ResourceManager.GetString("PopUpInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PopUpInsertSuccess {
            get {
                return ResourceManager.GetString("PopUpInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PopUpModifyFailed {
            get {
                return ResourceManager.GetString("PopUpModifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PopUpModifySuccess {
            get {
                return ResourceManager.GetString("PopUpModifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove news failed..
        /// </summary>
        public static string RemoveNewsFailed {
            get {
                return ResourceManager.GetString("RemoveNewsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove news succeed..
        /// </summary>
        public static string RemoveNewsSuccess {
            get {
                return ResourceManager.GetString("RemoveNewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemovePageFailed {
            get {
                return ResourceManager.GetString("RemovePageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemovePageSuccess {
            get {
                return ResourceManager.GetString("RemovePageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user failed..
        /// </summary>
        public static string RemoveUserFailed {
            get {
                return ResourceManager.GetString("RemoveUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user succeed..
        /// </summary>
        public static string RemoveUserSuccess {
            get {
                return ResourceManager.GetString("RemoveUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving news failed..
        /// </summary>
        public static string SaveNewsFailed {
            get {
                return ResourceManager.GetString("SaveNewsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving news succeed..
        /// </summary>
        public static string SaveNewsSuccess {
            get {
                return ResourceManager.GetString("SaveNewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SavePageFailed {
            get {
                return ResourceManager.GetString("SavePageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SavePageSuccess {
            get {
                return ResourceManager.GetString("SavePageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user failed..
        /// </summary>
        public static string SaveUserFailed {
            get {
                return ResourceManager.GetString("SaveUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user succeed..
        /// </summary>
        public static string SaveUserSuccess {
            get {
                return ResourceManager.GetString("SaveUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendContactFormEmailFailed {
            get {
                return ResourceManager.GetString("SendContactFormEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendContactFormEmailSuccess {
            get {
                return ResourceManager.GetString("SendContactFormEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendNewsletterEmailFailed {
            get {
                return ResourceManager.GetString("SendNewsletterEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendNewsletterEmailSuccess {
            get {
                return ResourceManager.GetString("SendNewsletterEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceProviderModifyFailed {
            get {
                return ResourceManager.GetString("ServiceProviderModifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceProviderModifySuccess {
            get {
                return ResourceManager.GetString("ServiceProviderModifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceProviderRemoveFailed {
            get {
                return ResourceManager.GetString("ServiceProviderRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceProviderRemoveSuccess {
            get {
                return ResourceManager.GetString("ServiceProviderRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceProviderSaveFailed {
            get {
                return ResourceManager.GetString("ServiceProviderSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceProviderSaveSuccess {
            get {
                return ResourceManager.GetString("ServiceProviderSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceTypeModifyFailed {
            get {
                return ResourceManager.GetString("ServiceTypeModifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceTypeModifySuccess {
            get {
                return ResourceManager.GetString("ServiceTypeModifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceTypeRemoveFailed {
            get {
                return ResourceManager.GetString("ServiceTypeRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceTypeRemoveSuccess {
            get {
                return ResourceManager.GetString("ServiceTypeRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceTypeSaveFailed {
            get {
                return ResourceManager.GetString("ServiceTypeSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ServiceTypeSaveSuccess {
            get {
                return ResourceManager.GetString("ServiceTypeSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsDeleteFailed {
            get {
                return ResourceManager.GetString("SettingsDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsDeleteSuccess {
            get {
                return ResourceManager.GetString("SettingsDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsInsertFailed {
            get {
                return ResourceManager.GetString("SettingsInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsInsertSuccess {
            get {
                return ResourceManager.GetString("SettingsInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsUpdateFailed {
            get {
                return ResourceManager.GetString("SettingsUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsUpdateSuccess {
            get {
                return ResourceManager.GetString("SettingsUpdateSuccess", resourceCulture);
            }
        }
    }
}
