//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.Resources.Logic", typeof(Logic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify news failed..
        /// </summary>
        public static string ModifyNewsFailed {
            get {
                return ResourceManager.GetString("ModifyNewsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify news succeed..
        /// </summary>
        public static string ModifyNewsSuccess {
            get {
                return ResourceManager.GetString("ModifyNewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user failed..
        /// </summary>
        public static string ModifyUserFailed {
            get {
                return ResourceManager.GetString("ModifyUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify user succeed..
        /// </summary>
        public static string ModifyUserSuccess {
            get {
                return ResourceManager.GetString("ModifyUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove news failed..
        /// </summary>
        public static string RemoveNewsFailed {
            get {
                return ResourceManager.GetString("RemoveNewsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove news succeed..
        /// </summary>
        public static string RemoveNewsSuccess {
            get {
                return ResourceManager.GetString("RemoveNewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user failed..
        /// </summary>
        public static string RemoveUserFailed {
            get {
                return ResourceManager.GetString("RemoveUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user succeed..
        /// </summary>
        public static string RemoveUserSuccess {
            get {
                return ResourceManager.GetString("RemoveUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving news failed..
        /// </summary>
        public static string SaveNewsFailed {
            get {
                return ResourceManager.GetString("SaveNewsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving news succeed..
        /// </summary>
        public static string SaveNewsSuccess {
            get {
                return ResourceManager.GetString("SaveNewsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user failed..
        /// </summary>
        public static string SaveUserFailed {
            get {
                return ResourceManager.GetString("SaveUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user succeed..
        /// </summary>
        public static string SaveUserSuccess {
            get {
                return ResourceManager.GetString("SaveUserSuccess", resourceCulture);
            }
        }
    }
}
